### PR TITLE
More tests

### LINKED ISSUE #22: Bucket region issue when Lambda triggers
When the Lambda triggers it looks like I am getting an error due to the region I deployed my infrastructure.

`  failed to upload report to bucket: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-east-2' status code: 400, request id: BC04B1B8AED32969, host id: Cx3IjHtCIrQnS0wX`

I set everything to build in `us-east-2`.  I am going to see if I cannot correct this by moving my S3 bucket for inventory to `us-east-1` as I suspect that is the issue.

### PR DESCRIPTION
**Pull request by briankfitzwater**
- Increases test coverage to 54.6%
- Adds note in README about default region being first in `regions` list (Closes #22)
- Uses tflint v0.13.1 instead of v0.9.2

### CODE REVIEW

**Comment by briankfitzwater** [comment]
[grace-inventory: Improve unit-test coverage](https://trello.com/c/TCimfTiH/1483-grace-inventory-improve-unit-test-coverage)

**Comment by briankfitzwater** [comment]
[grace-inventory: Bucket region issue when Lambda triggers (Issue #22)](https://trello.com/c/zbpW94mK/1486-grace-inventory-bucket-region-issue-when-lambda-triggers-issue-22)

File: handler/helpers/accounts/accounts.go [hunk 1]
```diff
@@ -56,16 +59,18 @@ type Svc struct {
 	iamSvc           iamiface.IAMAPI
 	organizationsSvc organizationsiface.OrganizationsAPI
 	downloaderSvc    s3manageriface.DownloaderAPI
+	stsSvc           stsiface.STSAPI
 }
 
 // NewAccountsSvc ... creates new Svc struct
 func NewAccountsSvc(cfg client.ConfigProvider) (as *Svc, err error) {
-	if cfg == nil {
+	if cfg == nil || reflect.ValueOf(cfg).IsNil() {
```
Comment (bryanlalexander) [inline handler/helpers/accounts/accounts.go]: Is there a situation where cfg would not be nil, but reflect.ValueOf(cfg) would be?

Comment (briankfitzwater) [reply handler/helpers/accounts/accounts.go]: That is an interesting question.  When I was writing the test I discovered cfg will never be nil because client.ConfigProvider is an interface{} type it will have a type and a value.

Comment (brady-gsa) [reply handler/helpers/accounts/accounts.go]: cfg has a value of nil, but cfg == nil is false because of its type?

Comment (bryanlalexander) [reply handler/helpers/accounts/accounts.go]: This is related to the default value associated with `sess` in his example code above. If he called `NewAccountsSvc(nil)` explicitly with `nil` we would follow the `cfg == nil` path. However, the default value of `var sess session.Session` is not really `nil`, as it does have an address assigned in memory.

Comment (brady-gsa) [reply handler/helpers/accounts/accounts.go]: I think we should just use the interface. The caller should use the interface and a factory method and we should do the same. The only other logical option I see is to follow a null object pattern and attach an isNil method to cfg. 

I think we can agree that two checks isn't something we want to propagate if we can avoid it - especially since it complicates testing. In this case did we test all branches of line 67? I think we'd actually have to add another test case that uses the interface to do so.

Comment (bryanlalexander) [reply handler/helpers/accounts/accounts.go]: We had a conversation about this and have decided it would be better to panic than obscure these situations by 'gracefully' handling `nil`.

Comment (briankfitzwater) [reply handler/helpers/accounts/accounts.go]: Since passing a nil is impossible the way we are consuming NewAccounsSvc(), we are moving the nil check.

**Comment by briankfitzwater** [comment]
@brady-gsa @bryanlalexander I still need someone to approve the PR...
